export const pieces: Record<string | number, TPiece> = {
  absurdism: {
    title: "Absurdism",
    date: "Spring 2019",
    description: "TODO",
    id: "absurdism",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/absurdism.jpg",
    series: "memePosters",
    type: "piece",
  },
  capitalism: {
    title: "Capitalism",
    date: "Spring 2019",
    description: "TODO",
    id: "capitalism",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/capitalism.jpg",
    series: "memePosters",
    type: "piece",
  },
  celebrity: {
    title: "Celebrity",
    date: "Spring 2019",
    description: "TODO",
    id: "celebrity",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/celebrity.jpg",
    series: "memePosters",
    type: "piece",
  },
  criticalMass: {
    title: "Critical Mass",
    date: "Spring 2019",
    description: "TODO",
    id: "criticalMass",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/critical_mass.jpg",
    series: "memePosters",
    type: "piece",
  },
  depression: {
    title: "Depression",
    date: "Spring 2019",
    description: "TODO",
    id: "depression",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/depression.jpg",
    series: "memePosters",
    type: "piece",
  },
  fame: {
    title: "Fame",
    date: "Spring 2019",
    description: "TODO",
    id: "fame",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/fame.jpg",
    series: "memePosters",
    type: "piece",
  },
  groupMentality: {
    title: "Group Mentality",
    date: "Spring 2019",
    description: "TODO",
    id: "groupMentality",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/group_mentality.jpg",
    series: "memePosters",
    type: "piece",
  },
  hate: {
    title: "Hate",
    date: "Spring 2019",
    description: "TODO",
    id: "hate",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/hate.jpg",
    series: "memePosters",
    type: "piece",
  },
  nostalgia: {
    title: "Nostalgia",
    date: "Spring 2019",
    description: "TODO",
    id: "nostalgia",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/nostalgia.jpg",
    series: "memePosters",
    type: "piece",
  },
  politics: {
    title: "Politics",
    date: "Spring 2019",
    description: "TODO",
    id: "politics",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/politics.jpg",
    series: "memePosters",
    type: "piece",
  },
  positivity: {
    title: "Positivity",
    date: "Spring 2019",
    description: "TODO",
    id: "positivity",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/positivity.jpg",
    series: "memePosters",
    type: "piece",
  },
  sexuality: {
    title: "Sexuality",
    date: "Spring 2019",
    description: "TODO",
    id: "sexuality",
    url: "https://storage.googleapis.com/sages_work_content/art/meme_posters/sexuality.jpg",
    series: "memePosters",
    type: "piece",
  },
};

export const series: Record<string | number, TSeries> = {
  memePosters: {
    title: "Meme Posters",
    date: "Spring 2019",
    description: "TODO",
    id: "memePosters",
    pieces: [
      pieces.absurdism,
      pieces.capitalism,
      pieces.celebrity,
      pieces.critical_mass,
      pieces.depression,
      pieces.fame,
      pieces.group_mentality,
      pieces.hate,
      pieces.nostalgia,
      pieces.politics,
      pieces.positivity,
      pieces.sexuality,
    ],
    type: "series",
  },
};

const media = { ...pieces, ...series };

export default media;
